export interface PlanItem {
  id: string;
  name: string;
  style: string;
  image: string;
  price: number;
  bedrooms: number;
  baths: number;
  floors: number;
  area: number;
  rating: number;
  reviews: number;
  badge: string;
  summary: string;
  featured?: boolean;
}

export const planCatalog: PlanItem[] = [
  {
    id: "modern-1",
    name: "Kenya Court Modern",
    style: "modern",
    image: "/herobg/hbg-1.jpg",
    price: 128000,
    bedrooms: 2,
    baths: 2,
    floors: 1,
    area: 92,
    rating: 4.7,
    reviews: 184,
    badge: "Compact build",
    summary: "A crisp starter plan with an efficient footprint for tight urban plots.",
    featured: true,
  },
  {
    id: "contemporary-1",
    name: "Ridge View Contemporary",
    style: "contemporary",
    image: "/herobg/hbg-2.jpg",
    price: 184000,
    bedrooms: 3,
    baths: 2,
    floors: 2,
    area: 184,
    rating: 4.8,
    reviews: 241,
    badge: "Balanced family plan",
    summary: "A bright double-storey layout with flexible living and work-from-home space.",
  },
  {
    id: "traditional-1",
    name: "Munyaka Traditional",
    style: "traditional",
    image: "/herobg/hbg-1.jpg",
    price: 149000,
    bedrooms: 3,
    baths: 2,
    floors: 1,
    area: 168,
    rating: 4.6,
    reviews: 163,
    badge: "Approval friendly",
    summary: "A grounded single-level layout with a straightforward, buildable shape.",
  },
  {
    id: "modern-farmhouse-1",
    name: "Mara Modern Farmhouse",
    style: "modern-farmhouse",
    image: "/herobg/hbg-2.jpg",
    price: 215000,
    bedrooms: 4,
    baths: 3,
    floors: 2,
    area: 248,
    rating: 4.9,
    reviews: 298,
    badge: "Top pick",
    summary: "Warm proportions, broad verandas, and a premium family-first layout.",
    featured: true,
  },
  {
    id: "farmhouse-1",
    name: "Highland Farmhouse",
    style: "farmhouse",
    image: "/herobg/hbg-1.jpg",
    price: 289000,
    bedrooms: 5,
    baths: 4,
    floors: 2,
    area: 336,
    rating: 4.9,
    reviews: 352,
    badge: "Family flagship",
    summary: "A generous farmhouse with big shared zones and private bedroom wings.",
  },
  {
    id: "bungalow-1",
    name: "Coastal Bungalow",
    style: "bungalow",
    image: "/herobg/hbg-2.jpg",
    price: 132000,
    bedrooms: 2,
    baths: 2,
    floors: 1,
    area: 124,
    rating: 4.5,
    reviews: 121,
    badge: "Easy living",
    summary: "A relaxed single-level plan with calm circulation and low build complexity.",
  },
  {
    id: "cabin-1",
    name: "Nakuru Cabin Retreat",
    style: "cabin",
    image: "/herobg/hbg-1.jpg",
    price: 165000,
    bedrooms: 3,
    baths: 2,
    floors: 1,
    area: 146,
    rating: 4.7,
    reviews: 176,
    badge: "Weekend retreat",
    summary: "A compact retreat with a warm silhouette and a grounded, private feel.",
  },
  {
    id: "country-1",
    name: "Green Acre Country",
    style: "country",
    image: "/herobg/hbg-2.jpg",
    price: 226000,
    bedrooms: 4,
    baths: 3,
    floors: 2,
    area: 276,
    rating: 4.8,
    reviews: 214,
    badge: "Best seller",
    summary: "Classic country scale with open social areas and generous bedroom zones.",
  },
  {
    id: "mediterranean-1",
    name: "Lakeside Mediterranean",
    style: "mediterranean",
    image: "/herobg/hbg-1.jpg",
    price: 342000,
    bedrooms: 5,
    baths: 4,
    floors: 2,
    area: 362,
    rating: 4.9,
    reviews: 367,
    badge: "Luxury coastal",
    summary: "A refined villa with a resort feel, flowing rooms, and strong curb presence.",
    featured: true,
  },
  {
    id: "victorian-1",
    name: "Royal Victorian",
    style: "victorian",
    image: "/herobg/hbg-2.jpg",
    price: 418000,
    bedrooms: 6,
    baths: 5,
    floors: 4,
    area: 448,
    rating: 4.8,
    reviews: 189,
    badge: "Statement build",
    summary: "A grand multi-level home for a large family or an elevated long-term build.",
  },
  {
    id: "modern-2",
    name: "Urban Courtyard Modern",
    style: "modern",
    image: "/herobg/hbg-1.jpg",
    price: 192000,
    bedrooms: 3,
    baths: 2,
    floors: 2,
    area: 208,
    rating: 4.7,
    reviews: 205,
    badge: "Smart footprint",
    summary: "A crisp city plan that balances privacy, airflow, and clean geometry.",
  },
  {
    id: "contemporary-2",
    name: "Skyline Contemporary",
    style: "contemporary",
    image: "/herobg/hbg-2.jpg",
    price: 258000,
    bedrooms: 4,
    baths: 3,
    floors: 2,
    area: 298,
    rating: 4.8,
    reviews: 233,
    badge: "High demand",
    summary: "A more expansive contemporary plan with strong indoor-outdoor flow.",
  },
];
